
mpi-BF: mpi-cpu_BF.cpp BF_file_io.h BF_file_io.cpp BF_custom_data_structures.h BF_print_functions.cpp BF_print_functions.h
	mpic++ -o MPI-CPU_BF mpi-cpu_BF.cpp BF_file_io.cpp BF_print_functions.cpp

