
mpi-Dijkstra: mpi-cpu_Dijkstra.cpp Dijkstra_file_io.cpp MinHeap.cpp Dijkstra_print_functions.cpp
	mpic++ -o MPI-CPU_Dijkstra mpi-cpu_Dijkstra.cpp Dijkstra_file_io.cpp MinHeap.cpp Dijkstra_print_functions.cpp

